### ISSUE TITLE
User card is not accessisble

### ISSUE THREAD

**Issue by fedi7777** [marcosgdf/dolibarr-otp#4]
Hi,

Everything went OK with installing the module, extracted, and activated on Dolibarr... when i go to User Card to generate the Code, i receive an error (500) saying that it's not accessible. 

And when i disable the OTP module, the Use Card page is accessible without problem.

Would you please help me solve this issue.

Thank you.

**Comment by marcosgdf** [comment]
Can you please tell me which error appears in your error.log file? And which version of Dolibarr are you using?

**Comment by marcosgdf** [comment]
Were you able to find the answer for my questions?
